[project]
name = "app"
version = "0.1.0"
description = "CSC Reporting Agent"
readme = "README.md"
requires-python = ">=3.11"
packages = ["app"]
dependencies = [
    "a2a-sdk>=0.2.6,<0.3.0",
    "click>=8.1.8",
    "httpx>=0.28.1",
    "langchain-google-genai>=2.0.10",
    "langgraph>=0.3.18",
    "langchain-openai >=0.1.0",
    "openai>=1.0.0",
    "pydantic>=2.10.6",
    "python-dotenv>=1.1.0",
    "uvicorn>=0.34.2",
    "a2a-mcp>=0.1.0",
    "fastmcp>=2.8.1",
    "google-adk>=1.4.1",
    "python-a2a>=0.5.9",
    "fastapi>=0.115.12",
    "pandas>=2.3.1",
    "pyodbc>=5.0.1",
    "sqlalchemy>=2.0.0",
    "neo4j>=5.0.0",
    "flask>=3.0.0",
    "gunicorn>=23.0.0",
    "requests>=2.32.0",
    "python-multipart>=0.0.20",
    "azure-identity>=1.19.0",
]

[tool.hatch.build.targets.wheel]
packages = ["app"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"